# Generated by Django 4.2.3 on 2023-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
        migrations.AddField(
            model_name='contact',
            name='registration_number',
            field=models.CharField(default='SomeDefaultValue', max_length=100, unique=True),
        ),
    ]
