# Generated by Django 4.2.3 on 2023-07-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_registration_number_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
