# Generated by Django 4.2.3 on 2023-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_used',
            field=models.BooleanField(default=False),
        ),
    ]
